### ISSUE TITLE
Aktive channels skal tjekkes periodisk via AMI for at undgå uoverenstemmelser

### ISSUE THREAD

**Issue by paf61** [DRB-IT/blacktiger#104]
For at undgå evt. fremtidige og lige nu uforudsete problemer som fx det i #103, skal AMI spørges med passende intervaller om aktive channels i hver konference.

Fx AMI-action ConfbridgeList med input fra ConfbridgeListRooms (som kun lister aktive konferencer). Man kunne fx tjekke alle konferencer hvert 5. minut, i en slags cleanup-job.

Ved mange hundrede konferencer i gang, kan der returneres omkring 2000 numre, så måske skal dette køres med en lav prioritet så det ikke går ud over andet blacktiger laver.

**Comment by paf61** [comment]
Vi får en sjælden gang imellem henvendelser som denne, så måske er dette issue stadig relevant.
--------------------------------------------------------------------------------
Sent: 27. januar 2015 22:11
Subject: RE: Driftstörningar

Hej! I kväll tisdag 27/1 så hade vi ett konstigt fenomen. hemsidan var öppen, Xlite igång och jag ringde upp från min smartphon och kunde lyssna men min uppringning registrerades inte på hemsidan. Vad kan det bero på?

**Comment by michaelkrog** [comment]
Det kan ikke hænge sammen med dette.

https://github.com/DRB-IT/blacktiger/issues/109 krævede en større renovering af kommunikationen med Asterisk og betød at det efterfølgende ikke bliver gemt andre oplysninger i hukommelsen end en liste over hvilke channels der er muted. Der er med andre ord ikke længere en liste med participants der skal synkroniseres. Events sendes direkte ud.

https://github.com/DRB-IT/blacktiger/issues/116 kunne til gengæld være aktuelt. Det drejer sig om at websocket'en holder op med at virke på serversiden selvom klienten ikke bliver disconnected. Vi oplevede den tidligere hvor du med en genstart løste problemet. Jeg har løst https://github.com/DRB-IT/blacktiger/issues/116 ved at opgradere Spring, da de havde issues på det der var løst i senere versioner end den vi brugte.

https://github.com/DRB-IT/blacktiger/issues/116 er en del af 2.0.10 releaset – jeg mener ikke at denne er installeret i test endnu.
