### ISSUE TITLE
Svagt login / stærkt login

### ISSUE THREAD

**Issue by michaelkrog** [DRB-IT/blacktiger#114]
Det er sandsynligt at man i en sal ønsker at se info om hvem der er på og/eller hvem der vil svare fra flere enheder(f.eks. talerpult), men det ikke er dem alle der skal kunne mute, kicke osv., er der behov for at man kan logge på med et alternativt password.

Det kunne fungere sådan her:
* Svagt login(readonly): Telefonnummer som password
* Stærk login(alm. login): Password som password.

**Comment by michaelkrog** [comment]
@paf61 Er der lavet understøttelse af dette i 'verify_hall_login' store procedure?

**Comment by paf61** [comment]
Nej - spørgsmålet er om vi behøver dette, efter vi har lavet løsningen med fluebenet der bestemmer om det er muligt at afbryde opkald. Jeg mener det er enklere at lade det være som det er nu, så der ikke er flere sæt kodeord.

**Comment by michaelkrog** [comment]
Jeg tror vi havde den op og vende i forbindelse med den mobile brugerflade - således at man kunne dele brugernavn/password ud til alle dem der ville bruge det på egen mobil men uden at de havde det rigtige login.

**Comment by paf61** [comment]
Nå ja, det står jo øverst i denne tråd - svagt login med telefonummer. Jeg synes ideen er god, men hvordan gør man muligheden synlig for brugerne, så de vil bruge den i stedet for det stærke kodeord?

**Comment by michaelkrog** [comment]
Hmm, ja. Måske de skulle have 2 sæt brugernavne og passwords, hvoraf det ene er fx. H45-9000-2 og det andet **S**45-9000-2 el. **V**45-9000-2 (**S**pectator eller **V**iewer) hvor den sidstnævnte (svage) bruger's password er, som du foreslog, telefonnummeret.

Den svage brugers password er lettere at huske og dermed lidt lettere at dele. Vi kunne enda informere det ud direkte i brugerfladen ved mikseren, da det kun ses efter korrekt (stærkt) login.

**Comment by michaelkrog** [comment]
Så vidt jeg husker har afdelingskontoret ønsket at der ikke bliver lavet en brugerfalde til pulten. Dermed forsvinder behovet for dette.
