### ISSUE TITLE
Opsummeret statistik

### ISSUE THREAD

**Issue by michaelkrog** [DRB-IT/blacktiger#120]
Der er behov for at kunne hente en opsummering af statistik.

Vi vil gerne have følgende opsummering ud:
* Antal sale
* Antal lyttere
* Antal lyttere på telefon
* Antal lyttere SIP
* Antal åbne mikrofoner

Disse info skal være tilgængelige for de globale tal samt specificeret ud for hver enkelt landekode.

**Comment by michaelkrog** [comment]
Forslag til JSON-model:

```javascript
{
    "all": {
        "halls": 1,
        "participants": 2,
        "participantsViaPhone": 1,
        "participantsViaSip": 1,
        "openMicrophones": 1
    },
    "+45": {
        "halls": 1,
        "participants": 2,
        "participantsViaPhone": 1,
        "participantsViaSip": 1,
        "openMicrophones": 1
    },...
}
```

**Comment by michaelkrog** [comment]
@paf61 @xToMMeRx 

I forbindelse med en opsummeret statistik, kan jeg så ALTID gå ud fra at en sal starter med H<landekode>, f.eks. H47-xxxx har altid landekode +47, H45 har altid landekode +45 osv?

Af alle de events der genereres i systemet, så er det kun ConferenceStartEvent, de kommer med alle oplysninger om rummet. Jeg kan selv slå oplysningerne, men det betyder blot et ekstra database opslag for hvert eneste event i systemet.

**Comment by xToMMeRx** [comment]
Ja, H45-xxxx vil altid have en +45 landekode, og det same med H46, H47 osv.

Men jeg forstår ikke helt hvorfor du spørger, hvad er det du har tænkt dig?
Er det fordi du fra ConferenceStartEvent får H45-xxxx nummeret, og så vil spare et databaseopslag for at finde ud af om det f.eks. er en dansk eller norsk sal (+45, eller +47 sal)?

**Comment by michaelkrog** [comment]
Ja, det er for at spare et opslag. 

For at lave opsummering vil jeg lytte på ConferenceStartEvent, ConferenceEndEvent, ConferenceMuteEvent, ConferenceUnmuteEvent, ConferenceJoinEvent og ConferenceLeaveEvent. Af de events er det kun ConferenceStartEvent der har detaljerede informationer om rummet(f.eks. telefonnummer of landekode). De andre events har kun rumnummeret.

Ud fra rumnummeret kan jeg lave et opslag for at få de detaljerede informationer – men hvis jeg alene ud fra rumnummeret kan afgøredet, så sparer jeg det opslag hver gang..

**Comment by xToMMeRx** [comment]
Okay, ja du kan sagtens bruge de første 3 karakterer af conference navnet (H45) til at bestemme landet, uden at lave databaseopslag.

Peter siger: Du skal bare lade de første 3 karakterer, H45, H46, H47 etc. stå i drop-down vælgeren istedet for at oversætte det til Danmark, Sverige, Norge eller +45, +46, +47.
På den made holdes det helt simpelt, så vi nemt kan udvide med et land mere uden at skulle rette noget i koden.

**Comment by michaelkrog** [comment]
Super.

Men skal jeg ikke lade det være 'H' efterfulgt af 1-3 cifre(Regexp: H[0-9]{1,3} ). Det kunne bære følgende:
* H1-xxxx (NANPA)
* H45-xxxx 
* H298-xxx

**Comment by michaelkrog** [comment]
Dette er delvist lavet nu og udstillet på /system/summary med ca76122. 
Følgende mangler:
* Indlæsning af data ved opstart af blacktiger så opsummering passer efter en genstart.
* Adskillelse mellem mødekonferencer og opkald fra salen.

**Comment by xToMMeRx** [comment]
Jo selvfølgelig - det mest korrekte ville nok faktisk være at tage alt med før bindestregen.

**Comment by michaelkrog** [comment]
Ja, det giver god mening. Det er det vi gør!

**Comment by michaelkrog** [comment]
Tilrettet med https://github.com/DRB-IT/blacktiger/commit/8fe7777f7c2263e852ecca2ef10816d8c7da6520
