### ISSUE TITLE
Mange warnings i loggen pga. custom mute property

### ISSUE THREAD

**Issue by michaelkrog** [DRB-IT/blacktiger#126]
Der er lavet en custom property i Asterisk der angiver om en lytter er muted eller ej. Men som udgangspunkt kan de ikke konverteres til et ConfbridgeListEvent. Istedet kommet følgende i loggen hver gang:
```
WARN EventBuilderImpl:110 - Unable to set property 'muted' to 'No' on org.asteriskjava.manager.event.ConfbridgeListEvent: no setter. Please report at http://jira.reucon.org/browse/AJ
```

Det skal undersøges om der kan laves en ny klasse der extender ConfBridgeListEvent der kan registreres i [EventBuilder'en](https://github.com/srt/asterisk-java/blob/master/src/main/java/org/asteriskjava/manager/internal/EventBuilderImpl.java). Hvis det kan lade sig gøre kan behøves denne info ikke længere at holdes opdateret i et map i blacktiger.

**Comment by michaelkrog** [comment]
@xToMMeRx Er der mulighed for at den 'muted' variable du har angivet i asterisk også kommer med ud på ConfbridgeJoinEvents?

**Comment by xToMMeRx** [comment]
Jeg sætter ikke bevidst nogen variable for muted i Asterisk. Det eneste der er sat i forhold til mute er at ConfBridge er konfigureret til at alle lyttere skal joine muted.

Så vidt jeg kan se er der ingen mulighed for at få en Event når en bruger mutes eller unmutes i Asterisk 11, det bliver du nød til selv at holde styr på med det udgangspunkt at hvis det er en lytter (eller en sal som ringer op til en anden conference) starter de muted, og hvis det er en sal som ringer op til sin egen conference starter en unmuted.
Det ser ud til at muligheden er kommet i Asterisk 13 (se Event_ConfbridgeMute og Event_ConfbridgeUnmute på https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+AMI+Events)
Jeg ved ikke om denne Event kun kommer hvis brugeren selv unmuter eller muter, eller den også kommer når det gøres via AMI, men uanset hvad kommer muligheden først når vi engang bygger en ny servere baseret på Asterisk 13.

**Comment by michaelkrog** [comment]
Ok. Det har jeg misforstået så. Hvis jeg telnet'er ind og hente en liste over deltagere på min lokale maskine får jeg følgende:
```
Action: ConfbridgeList
Conference: H45-0000-1

Response: Success
EventList: start
Message: Confbridge user list will follow

Event: ConfbridgeList
Conference: H45-0000-1
CallerIDNum: H45-0000-1
CallerIDName: Hall 45-0000-1
Channel: SIP/H45-0000-1-0000000e
Admin: No
MarkedUser: Yes
Muted: No

<flere events...>
```

Jeg havde bildt mig ind at den `Muted: No`kom fra noget script du havde lavet. :)  

Jeg har indtil nu selv holdt styr på det, men ville ændre det til blot at bruge den info fra Asterisk – men den kommer kun på ConfbridgeList og ikke f.eks. ConfbridgeJoin, så jeg bliver stadig nødt til at holde styr på det selv.
