### ISSUE TITLE
Logning af svarfunktion

### ISSUE THREAD

**Issue by paf61** [DRB-IT/blacktiger#132]
Til brug for statistik skal svarfunktion logges. Der er fire events der kan logges:
"Keypress 0"
"Keypress 1"
"Unmute"
"Mute"

Den nye procedure write_caller_events_log har the parametre (+ key):
1) sal (SIP-id)
2) lytter (SIP-id)
3) én af de fire events ovenfor (som tekststrenge)

Eksempel med opkald fra fastnet:
call write_caller_events_log("H45-1234","+4512345678","Keypress 1",key);

Eksempel med opkald fra computer:
call write_caller_events_log("H45-1234","L123456789","Unmute",key);

**Comment by michaelkrog** [comment]
Hej @paf61 og @xToMMeRx 

Har I et godt input til hvordan man fra et channel kan anmode asterisk om callerIdNum? Et DTMF event giver ikke info om callerIdNum.
https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+ManagerEvent_DTMF

**Comment by michaelkrog** [comment]
FYI: Det ser ud til at være kommet med i Asterisk 12:
https://wiki.asterisk.org/wiki/display/AST/Asterisk+12+ManagerEvent_DTMFBegin

**Comment by michaelkrog** [comment]
Mangel på callerIdNum gør sig pt. også gældende ved Mute/Unmute. Klienten(blacktiger-controller) angiver kun channel i forbindelse med Mute/Unmute. Efter at Mute/Unmute er gennemført er jeg derfor nødsaget til at sprøge Asterisk hvad callerIdNum er for at kunne logge den info.

Fra Asterisk 12 senderAsterisk imidlertid et Mute/Unmute event når det er gennemført og det indeholder callerIdNum: https://wiki.asterisk.org/wiki/display/AST/Asterisk+12+ManagerEvent_ConfbridgeMute

**Comment by paf61** [comment]
Når "vil gerne svare" og mute/unmute pushes til websiden er de events jo mappet til SIP-id'et (ellers kan det jo ikke vises på websiden), så kan det ikke logges på det sted?

**Comment by michaelkrog** [comment]
Desværre nej. 

Mapningen mellem SIP-id eksisterer pt. kun i Asterisk og i browseren. Den eneste information som blacktiger-serveren gemmer er om den enkelte channel er muted eller ej(kun nødvendigt med Asterisk 11, ikke med Asterisk 12). Al andet info fra asterisk bliver blot sendt igennem, evt. dekoreret med info fra telefonbogen.

Pt. når browseren sender et mute/unmute request så sender den kun 'channelid' for den channel der skal mutes/unmutes. Men da blacktiger ikke holder på noget information, så ved den ikke noget om sipid for det channelid. Det ved kun Asterisk.

Jeg kan lade blacktiger holde på en liste over alle aktive channels og det tilknyttede sipid. Men vi skal blot holde i tanke at det, ligesom med mute/unmute informationerne, er en lap for noget der bliver løst når/hvis vi opgraderer til Asterisk 12. Asterisk 12 genererer nemlig events for mute/unmute som indeholder de informationer vi har behov for. Asterisk 11 genererer slet ikke events for mute/unmute.

**Comment by paf61** [comment]
Eventuelt kan vi vente med at få sal og callerID på til når vi har opgraderet til Asterisk 12 (måske inden åretes udgang, hvor support på 11 stopper). Felterne kunne så indtil videre stå blanke, og channelID kunne midlertidigt tilføjes efter status-strengen. Om ikke andet kan vi så se mængden af svar totalt, og ud fra channelID kunne vi manuelt finde ud af hvor mange forskellige lyttere det er.
